Reference page
https://docs.docker.com/engine/reference/builder/


Docker can build images automatically by reading the instructions from a Dockerfile.

Example dockerfile:

FROM node:16

WORKDIR /usr/src/app

COPY --chown=node:node  . .

RUN npm ci

ENV DEBUG=playground:*

USER node

CMD npm start
