# For reference see https://docs.docker.com/compose/compose-file/03-compose-file/

version: '3.8'

services:
  app:
    image: server
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    